project_name: tw
before:
  hooks:
  - go mod tidy

release:
  github:
    owner: embano1
    name: tw
  name_template: '{{.Tag}}'
  draft: false
  
brews:
  - ids:
      - tw
    tap:
      owner: embano1
      name: homebrew-tw
    commit_author:
      name: goreleaserbot
      email: embano1@live.com
    install: |
      bin.install "tw"
    test: |
      system "#{bin}/tw -v"
    homepage: "https://github.com/embano1/tw"
    description: "'tw' is a very basic Twitter client to query your Likes, and do some powerful JSON filtering."
    
builds:
  - id: tw
    goos: &goos-defs
      - linux
      - darwin
      - windows
    goarch: &goarch-defs
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: tw
    
archives:
  - id: tw
    name_template: "tw_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements: &replacements
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: "{{ .Tag }}-next"
  
checksum:
  name_template: checksums.txt'
  
dist: dist

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch