name: Build

on:
  push:
    branches: ["main", "master"]

  pull_request:
    branches: ["main", "master", "release-*"]
  
  workflow_dispatch:

jobs:
  artifacts:
    name: Create Artifacts (no push/upload)
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: ["1.18"]
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # no push
          args: release --rm-dist --snapshot --release-notes RELEASE_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify git clean
        shell: bash
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "${{ github.repository }} up to date."
          else
            echo "${{ github.repository }} is dirty."
            echo "::error:: $(git status)"
            exit 1
          fi

      - name: Archive goreleaser artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/tw*x86_64*.tar.gz
            dist/checksums.txt
          retention-days: 1
